server:
  port: 9090

spring:
  application:
    name: rental-service
  datasource:
    username: koon
    password: vdOoBgzLV6SvB8lgC20s
    url: jdbc:postgresql://localhost:5432/rental
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
